# Generated by Django 5.2.7 on 2025-11-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imdbrating',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='imdbrating',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='track_number',
        ),
        migrations.AlterField(
            model_name='imdbrating',
            name='rating',
            field=models.FloatField(),
        ),
    ]
